DROP DATABASE IF EXISTS fourcheball;
CREATE DATABASE fourcheball SET 'utf-8';
CREATE TABLE l1_ranking_hist(
 	AS_OF_DATE DATE
	,AS_OF_EXTRACTION INTEGER
	,TEAM_RANK INTEGER
	,TEAM_NAME VARCHAR(25)
);


